import pandas as pd
import os
from glob import glob

# Step 1: Define path and company list
folder = r'C:\vs_code\TenderHunter2.1.3\final\paladiam\result'

raw_text = """  
3COP SECURITY SOLUTIONS
6X
A B ENTERPRISES
A M ENTERPRISES
A-Z OFFICE SUPPLIERS
A. M. Business Solutions
A.K.TRADE AGENCY
A.N. PHARMA
A.V.M. SALES CORPORATION
AAA SPINNERS
AADINATH AGENCY
AADINATH PERIPHERALS AND CONSUMABLES
AADRIKA AUTOMATION
AAN Associates
AASHA ENTERPRISES
AAYAT ENTERPRISES
ACCORD COMMUNICATIONS LIMITED
ACE BUSINESS SOLUTIONS
ACUBEAVENUE TECHNOLOGIES
AD ASSOCIATES
ADDSOFT TECHNOLOGIES PRIVATE LIMITED
ADVANCE INFOSOLUTIONS PRIVATE LIMITED
AFZAL HUSSAIN SHAH
AGR TRADE LINK
AGRAWAL ENTERPRISES
AGS ENTERPRISES
AHR ENTERPRISES
AJAY ENTERPRISE
AKASH ENTERPRISES
ALLIED ENGINEERING DEVELOPERS
ALPHA TRADERS
AMAN ASSOCIATES
AMBICA STATIONERS
AMBIKA ENTERPRISES
AMERICAN MEDITEK SYSTEMS PRIVATE LIMITED
AMPRESS ELECTRICAL ENGINEERS & CONSULTANTS
ANADI ENTERPRISES
ANTRIKSH TECHNOSYS PRIVATE LIMITED
ANTRIX INFRATEL PRIVATE LIMITED
ANVI ENTERPRISES
AONE TRADING
AR ENTERPRISES
ARTI TRADERS
ARUNA'S STORE
ARUP JYOTI SAIKIA
ARYA INFRATECH
ARYAN ENTERPRISES
ASHA MEDICAL STORE
ASSET DIET CO
AUTONICS MACHINES INDIA PRIVATE LIMITED
AV BUSINESS SOLUTIONS
AV CONSTRUCTIONS AND SUPPLY
AVTARS ENTERPRISES
AVYLIN'S COLLECTION
AYUSHI ENTERPRISES
Aarti PlayGroup Solution
Alfa Biomedical Co
Arbind Enterprise
B K ENTERPRISES
B K THAPAR HOSIERY WORKS
B. L. CORPORATION
B.S CONSTRUCTIONS
BABITA ENTERPRISES
BAGRI TELECOM
BAJRANG TRADERS
BALAJI ENTERPRISES
BALAJI TEXTILES
BELHO Enterprise
BENCH MARK INFOTECH SERVICES PRIVATE LIMITED
BEST & BEYOND
BEST SECURITY SERVICES
BGS ENTERPRISE
BHAGWATI RUBBER WORKS
BHARDWAJ TRADING COMPANY
BHAT MUSHTAQ HARDWARE STORE
BHAT TRADERS
BHATI BUSINESS SYNDICATE
BHATTACHARJEE AND CO
BLISS ENTERPRISES
BLUE SQUARE
BODY POWER FITNESS AND SPORTS
BOWNINJA ARCHERY
BROINFOTECH
Bharat Enterprise
Bhasin Industries
Bhavya Advertising
Binod kumar Karnani
Bothra Enterprises
Bulaqi Dass Singhal and Sons
CAMEL FARMS AND FINANCE PRIVATE LIMITED
CH JAGANNATH MADANLAL
CHANCHALA THAKUR
CHANDAN KUMAR
CHANDRA DRUG DISTRIBUTORS
CHANDRA OVERSEAS
CHANDRESWAR SINGH
CHIPS CARE
CHOWDHARY ENTERPRISES
COMPUTER AT A GLANCE
COMPUTORIUM
COMPUZER SOLUTIONS PRIVATE LIMITED
CONTINENTAL MILKOSE
CORE TECHNOLOGIES
CREST ENTERPRISES
CRYSTAL WORKS
CSA CORPORATION PRIVATE LIMITED
CYBER VALLEY
D N D ASSOCIATES
D R MERCANTILE
D. K. ENTERPRISE
DAR HARDWARE STORE
DEB VARIETIES
DECAGRID SUPPLIES & SERVICES PRIVATE LIMITED
DEEPAK ENTERPRISE
DEEPIKA ASSOCIATES
DELVI TREXIM
DERPA INDUSTRIAL POLYMERS PVT LTD
DEV ENTERPRISES
DEV RAJ SAMBYAL
DEVKRIPA ENTERPRISES
DHRUVA TRADARS
DIAGNOSTICMED
DIGITAL COMPUTER SOLUTIONS
DRESS CODE CLOTHING PRIVATE LIMITED
DSB RESOURCES LLP
DUBARIA COMPUTERS PRIVATE LIMITED
DUROLAC
DX ARCHERY EQUIPMENTS
Darshan Traders
Deep Systems & Solutions
Dosti Stationery Stores
EASTERN TRADE AGENCY
EASYWAY ENTERPRISES
EEKAKSHARA PROJECTS PRIVATE LIMITED
ELECTRO SPORT INDIA
ELEKTRONIK LAB
ELITE BIOTECH
ERA GLOBAL STANDARDS CERTIFICATION PRIVATE LIMITED
ESDS SOFTWARE SOLUTION LIMITED
ESHANI TRADING
ESS KAY HOME CARE
ESTEEM360 ZONE PRIVATE LIMITED
ESWAR ENTERPRISES
EWIT
EX SERVICEMAN ENTERPRISES
EXICOM TECHNOLOGIES INDIA PRIVATE LIMITED
Easy Solution & Services
F I ENTERPRISES
FIRDOUS AND CO
FLUX NETWORK SOLUTIONS
FOXSKY ELECTRONICS INDIA PRIVATE LIMITED
FRIENDS AUTOMOBILES
G P Enterprise
G S L ENTERPRISE
G.D ENTERPRISE
GANPATI INTERGLOBE PRIVATE LIMITED
GARAI ENTERPRISES
GARG ASSOCIATES
GARV ENTERPRISES
GATE CONSULTING PRIVATE LIMITED
GAURAV SERVICES
GAUTAM TRADER
GAYATRI LUBRICANTS
GCS PROTECH ENGINEERING PRIVATE LIMITED
GEE AAR CORPORATION
GENESIS NETWORK
GLOBAL TRADE SOLUTIONS
GLOBAL TREXIM
GM TRADING CO
GRAYEYE IT SYSTEMS PRIVATE LIMITED
GUPTA TRADERS
GURJYOT ENTERPRISES
Gatiman Traders
Golden Bharat Sales Corporation
Gupta Enterprises
H.B ENTERPRISE
H.H.MARKETING
H.P.SINGH MACHINERY PVT LTD
H.R. ENTERPRISE
HANS RAJ
HANUMAN UDYOG
HANUMANBUX UMADUTT
HARDIK ENTERPRISES
HARTREE ENERGY SYSTEMS PRIVATE LIMITED
HI-TECH REPROGRAPHICS
HILLS STATIONERS & PRINTERS
HILTON AGRO FOODS PRIVATE LIMITED
HIND ENTERPRISES
HINDUSTAN TECHNICAL WORK
HITESH AGENCY
HOME DECOR SUPERSTORE
HRISHITA PRIVATE LIMITED
HUE SERVICE PRIVATE LIMITED
HUNDAL DENTAL TRADERS
HYDERABAD FOOD PRODUCTS PVT LTD
Hanuman supply corporation
I-R-M ENTERPRISES
I-View Technologies
ICARE IT SOLUTIONS
ICON POWER SOLUTIONS PRIVATE LIMITED
IJ ENTERPRISES
IND MICRO DEVICES
INDO FOOD FLAVOURS
INFINITY
INTELID INDIA PRIVATE LIMITED
INTERNATIONAL TRADE CENTRE
INTIME COMMOTRADE PRIVATE LIMITED
INTRAXIS SPICES PRIVATE LIMITED
IQBAL TRADERS
IRSHAD AHMED
ISLAND LALOO
IT VISION
Indian Canvas Industries
Infinity Enterprise
Insight Saket Enterprises
J B EQUIPMENTS
J B TRADERS
J,M TRADERS
J. K ENTERPRISE
JAAPI GREEN PRODUCTS LLP
JAI BALAJI MARKETING
JAIGAON SALES
JALARAM TREDARS
JANKI ENTERPRISES
JE PREFAB INFRA PRIVATE LIMITED
JEETU TRADERS
JHARNESHWAR GLOBAL PRIVATE LIMITED
JIWANRAM BINOD KUMAR
JK HEAVY GARAGES
JMM INFRACON
JUNED BAJEWALA & SONS
JYOTI ENTERPRISES
JYOTI PHARMACEUTICALS
JYOTI WOOLLEN MILLS
Jet Age Garage Equipments
K B ACTIVE CARBON
K B ENTERPRISES
K U ENTERPRISES
K.A.ENTERPRISES
K.D E MARKETPLACE
K.L. EQUIPMENTS
K9 WARRIORS PRIVATE LIMITED
KALA ENTERPRISES
KAMDHENU ENTERPRISE
KAP CONSTRUCTION
KARNI AGENCY
KASHVI ENTERPRISE
KDB INFOCOM PRIVATE LIMITED
KESHAR TRADING COMPANY
KHALSA GYMNASTIC WORKS
KHALSA TRADING
KHANDAL SUPPLIERS
KHUSHI COMPUTERS
KIRAN ENTERPRISES
KRISHA BUSINESS LLP
KRISHNA ENTERPRISES
KRISHNAYAN INDUSTRIES
KRITIKA MEDI PHARMA
KUSHSURY ENGINEERS LLP
Kailash and Sons
Kamakhya Trading Co.
Keshav Trading Co.
LA INTERNATIONAL GENERAL ORDER SUPPLIER
LAL ENTERPRISES
LAL PET PRODUCTS
LAMBODHAR ENTERPRISE
LANDMARK COMPUTER PRINTS
LAXMI KAPAT PRIVATE LIMITED
LAXMI STORES
LE MERITE EXPORTS LIMITED
LEELA TRADING COMPANY
LEPAKSHI ENTERPRISES
LEVEL OFFICE SYSTEMS
LIFESTYLE WONDER
LNH ENTERPRISE
LOGIX NET SOLUTIONS PRIVATE LIMITED
LOREX INFOTECH
LUBEKART SALES INDIA PRIVATE LIMITED
LUXMI ENGINEERS
Lifestyle Fitness Co.
Lucky Enterprises
M S DRT Enterprise
M S ENTERPRISES
M SABIR BAJEWALA
M.K MOBILE
M.K.ENTERPRISES
M.P.ENTERPRISE
M/O ILLHUM ENTERPRISES
M/S ADARSH SALES CORPN
M/S ASTER GM
M/S BATHWORLD
M/S BHARAT KUMAR
M/S BHARTI TRADERS
M/S CARON ENTERPRISES
M/S DEEPAK ENTERPRISES
M/S EAST WEST TANNERS
M/S EMBOSS ENTERPRISES
M/S FAROOQ AHMAD KAK
M/S FITNESS CORNER
M/S G. M. ENTERPRISES
M/S G. N. TRADERS
M/S GAJRAJ ENTERPRISES
M/S GANGA ENTERPRISES
M/S GAURAV CONSTRUCTION
M/S GUPTA MOTOR
M/S HAKEEM MEDICAL HALL
M/S HARMEET KAUR SEHGAL
M/S INFINITY
M/S K.B ENTERPRISES
M/S KALA ENTERPRISES
M/S KANISHKA ENTERPRISE
M/S KAUSHAL AGENCIES
M/S KEVICHOL SOPHIE
M/S KRITIKA INDUSTRISES
M/S LIPIKA ENTERPRISE,GOROIMARI,AHOM CHUBURI,SONITPUR.
M/S LOTHA TRADING CO.
M/S M.K. AUTOMOBILE
M/S M.K. TRADERS
M/S MAA BIPULA ENTERPRISES
M/S MAA TELECOM NETWORK
M/S MAKMONI ENTERPRISES
M/S MAMTA PRODUCTS
M/S MANASH COMUNICATION
M/S MANJIT AUTO SALES
M/S MARATHON STORES
M/S MB ENTERPRISES
M/S MIR & COMPANY
M/S N. AVIKHU ZHIMOMI
M/S NARESH BROTHERS
M/S NAVSHEEN ASSOCIATES
M/S NEW AGE MARKETING
M/S Om Traders
M/S P K ELECTRONICS
M/S PAREEK ENTERPRISES
M/S R P INDUSTRIES
M/S R.S TRADING
M/S RABINDERJIT SINGH & SONS
M/S RADHA SHYAM ENTERPRISE
M/S RAHUL TRADING COMPANY
M/S RAKESH SINGH SHEKHAWAT
M/S RAM BABU YADAV
M/S RAMAWATAR SINGH
M/S RAVINA ENTERPRISE
M/S RIDHI AGENCY
M/S SALOMI MASAHARI
M/S SANJAYKUMAR SINGH
M/S SANNA ENTERPRISES
M/S SANTOSH KUMAR MADEASIA
M/S SAROJ ENTERPRISE
M/S SATPAL ENTERPRISES GENERAL ORDER SUPPLIERS
M/S SATURN ENTERPRISES
M/S SAWAI SINGH
M/S SHAKTI CONSTRUCTION & SUPPLY CO.
M/S SHEIKH ENTERPRISES
M/S SHIV SHAKTI DISTRIBUTORS
M/S SHREE HANUMAN TRADERS
M/S SHREE SHANTI STATIONERY
M/S SRI BALAJI ENTERPRISE
M/S STANLEE MAHONGNAO
M/S SUCHI ENTERPRISES
M/S SUN ENTERPRISES
M/S SUNDARAMM
M/S SUVA STAR ENTERPRISES
M/S SYSTEM INTEGRATOR
M/S Sati Enterprise
M/S TECHNO PROJECT SOLUTION
M/S TEN RING SPORTS
M/S TOHOKHU T SEMA
M/S TOVISHE ACHUMI
M/S U.V. TECHNO
M/S UMA ENTERPRISES
M/S V M ENTERPRISE
M/S VOICE COMMUNE
M/S YAJAT ENTERPRISES
M/S YOGESH CHANDRA AGARWALA
M/S YOGITA ENTERPRISES
M/S. A7 ENTERPRISES
M/S. ARCHITEVO TRADERS
M/S. GANDHESWARY BHANDAR
M/S. GARG GENERAL STORE
M/S. HBM ENTERPRISE
M/S. MODERN MACHINERY STORES
M/S. MUNNI KANWAR
M/S. SHUBHASHISH MUKHERJEE
M/S. TANWAR TRADERS
M/S. UDAY KUMAR SINGH
M/S. UMRAO LAL GOYAL & SONS
M/S.AALEM AGENCY
M/s Fortune Trading
M/s Gujar & Son's Enterprises
M/s Harish Kumar Kushwaha
M/s Mahesh Kumar Gupta
M/s PATWARI & CO
M/s RAINA AND SONS
M/s S S Traders
M/s SARNA ASSOCIATES
M/s SHREE BALAJI TRADERS
M/s Tezpur Kalakrite
M/s VIKESH KUMAR SECURITY AGENCY
M/s. Jamuna Enterprises
M/s.B.K. JHA
M/s.ZUHOLI SUMI
MAA CHANDI ENTERPRISE
MAA DURGA ENTERPRISE
MAA ENTERPRISE
MAA SHAKAMBARI SUPPLIER
MAA VAISHNO ENTERPRISES
MAANVIK TRADING
MAHADEV ENTERPRISES
MAHAGOURI ELECTRICAL PRIVATE LIMITED
MAHAJONG COKE LLP
MAHAKALI COMPUTER & STATIONERS
MAHALAXMI TOOLS
MAHI ENTERPRISES
MALHOTRA TRADERS,
MANIFEST ENTERPRISES & CO
MANISHA TRADING COMPANY
MANOJ ENTERPRISE
MARAK SUPPLY & AGENCIES
MARK MATRIX SECURITY SOLUTIONS
MARUTI MARKETING
MBB ENTERPRISES LLP
MD ABDUL MATIN
MEDILOGY BIOTECH
MEERA SUPPLIERS
MEGHALAYA CONSTRUCTION & SUPPLY CO.
MIHIR COMPUTERS.
MIKADO ENGINEERS
MINAS STORES
MISHKA TRADECON PRIVATE LIMITED
ML SONS
MN ENTERPRISES
MOGAL TRADERS
MOHAMMAD ISHAQUE
MR Technologies
MRP TELECOM SOLUTIONS
MS AWINASH ENTERPRISES
MS BISHAKA JAIN
MS ENTERPRISES
MS Prateeka Enterprises Company
MURTSEY ENGINEERING WORK
Maa Kali Enterprises
Mahi enterprise
Majestic Enterprises
Mangal Enterprise
Mangla Plastic Industries
Mannat Electronics
Ms NEW CROSSLAND PRODUCTS
Ms S M ENTERPRISES
Multiventure Group of companies
N D ENTERPRISES
N E ENTERPRISES
N H Enterprises
N K MARKETING
NAKSHAMAKERS
NAMAN INTERNATIONAL
NAMO
NANAK TRADERS
NANDA AGROTECH PRIVATE LIMITED
NASKAR ENTERPRISE
NATRAJ GAS
NAVKAR INFOMEDIA
NCS ENTERPRISES
ND SPICES PRIVATE LIMITED
NEAL ENTERPRISES
NECTAR INFOSYSTEMS INDIA PRIVATE LIMITED
NEELKANTH TRADER
NEHA ENTERPRISES
NET-LINK INFORMATION TECHNOLOGY PRIVATE LIMITED
NEW AHANGER ENTERPRISES
NEW FAKHRI STORES
NEW WHITE GOLD PRIVATE LIMITED
NICE INFOTECH
NORTH EAST ENVIRO TECH PRIVATE LIMITED
NORTH EAST TRADE CENTRE
NORTHERN ENTERPRISES
NR Solutions
NSK ENTERPRISE
NUABLE TECHNOLOGIES PRIVATE LIMITED
NandAnand Co.
Neelam Enterprises
Nirmala Medical Store
O.P ENGINEER'S
OANDUM SOLUTIONS LLP
OFFICEBAZZAR E-STORE PRIVATE LIMITED
OMEGA ENTERPRISES
OMKAR STEEL WORKS
OSSDEN PAPER
OVERSEAS TRADERS
OWAIS CLINICAL LAB
PACIFIC COMPUTER
PALAK ENTERPRISES
PAN INTELLECOM LIMITED
PARV ENTERPRISES
PASUPATI EXPO INDIA PRIVATE LIMITED
PATEL MEDICARE
PAVANI ENTERPRISES
PAYAL ENTERPRISE
PHARMACHEM
PILKHUWA WATER PROOFING COMPANY PRIVATE LIMITED
PINTU KUMAR JHA
PIYUSH ASSOCIATES
PRAKASH STORES
PRATIMMA ENTERPRISE
PRATYAKSH ENTERPRISES
PRIYANKA ENTERPRISE
PROMAK RETAIL
PUNJAB WOOL SYNDICATE
Preferred Seven Technologies
R B TRADERS
R G S Enterprise
R M ENTERPRISE
R S TRADE & AGENCY PRIVATE LIMITED
R.S. BAJAJ TEA COMPANY
RAAJAS INDIA PRIVATE LIMITED
RADHA KISHAN GOBIND RAM LTD
RADHA TRADING COMPANY
RAHUL TRADERS
RAILQUANT TECHNOLOGY & SERVICES
RAJASTHALI TEXTILES & GEMS PALACE
RAJESH ENTERPRISES
RAM PRAVESH
RAMYA ENTERPRISES
RARA SUPPLY
RATHI ENTERPRISE
RAUSHEENA UDYOG LIMITED
REAL ETERNITY
RELIANCE ADVERTISING & MARKETING AIDS
RESHI CONSTRUCTIONS AND SERVICES PRIVATELIMITED
RHINO DISTRIBUTORS
RIANNA INDUSTRIES
RIKI SECURITY SOLUTIONS PRIVATE LIMITED
RISHAV ENTERPRISES
RNY & SONS
ROHIT STEEL INDUSTRIES
RONAK SINGH
ROYAL ENTERPRISES
ROYAL ENTRADE
ROYAL PHOTOSTAT
ROYAL PRINT TECHNOLOGY
RSP IT SOLUTION
RYAN ENTERPRISES
Raju Fabrication Company
Ramen and Jhulan Traders
S K & COMPANY
S K AGENCY
S K ENTERPRISES
S M Enterprises
S R AUTO RICE MILL
S R INSTRUMENT
S. C. ENTERPRISE
S. G. ENGINEERS
S. TRADERS
S.K.S.ENTERPRISES
S.P. INFRA
S.S TRADERS
S.S. Enterprises
SAGAR SAROVER
SAHANI STEEL FURNITURE
SAHAY ENTERPRISES
SAHIB ENTERPRISES
SAKSHI SALES CORP.
SALONAIDE
SAMIR BOOK STALL
SAMPAN INFRA SOLUTION
SAMRAT INDER SINGH
SAMSARA ENTERPRISE
SANCHAR WIRELESS COMMUNICATIONS LIMITED
SANDEEP KUMAR AGRAWAL
SANTOSH ENTERPRISES
SARAF FURNITURE
SATYAM CONTRACTORS PRIVATE LIMITED
SBHIPL
SBL PLASTICS PRIVATE LIMITED
SCALENOW INDUSTRIES LLP
SENGUPTA ENTERPRISES
SHAKAMBARI INTERNATIONAL PRIVATE LIMITED
SHARMA COMPUTERS
SHARMA TRADER
SHAW ENTERPRISE
SHEORAN ENTERPRISES
SHIV TRADERS
SHIVA TRADERS
SHREE HANUMANTH TRADING
SHREE KRISHNA TRADING
SHREE M TECHNOLOGIES
SHREE MAA UDHYAM
SHREE MARUTI ASSOCIATES
SHREE SAI ENTERPRISES
SHREE SATI TRADERS
SHREE SAYAM ENTERPRISES
SHREE VINAYAK ENTERPRISES
SHRI LALSHAH PAPERS PRIVATE LIMITED
SHRI RAM ENTERPRISE
SHRI RAMJI ENTERPRISES
SHRI STERON KHARJANA
SHRI SUBHASH AGARWALLA
SHRI SURYA TECHNOLOGY
SHWETA ENTERPRISES
SHYAM DEV SINGH
SIANG TRADERS
SIDDHI ENTERPRISES
SIDDHI SERVICES
SINGH AND COMPANY
SINGH DYE CHEM
SINHA ENTERPRISE
SITA RAM PRADEEP KUMAR
SIXTEEN DIRECTIONS HOMECARE PRIVATE LIMITED
SK Enterprises
SKY VENTURES
SMG ENTERPRISES
SMT. NANDITA MARBANIANG
SOCIETY MARGIN FREE PAINTS SUPER MARKET
SOLUTION CARE
SONAL ENTERPRISES
SOURCE DOT COM PRIVATE LIMTED
SP ENTERPRISES
SPARES HOUSE
SPS TRADING
SR ENTERPRISE
SREE RAM ASSOCIATES
SREE SAI BALAJI ASSOCIATES
SRI BIPIN HOREN INFRATECH PRIVATE LIMITED
SRI JUGAL BARUAH , KUMARGAON, TEZPUR.
SRI LOKENATH AUTOMOBILE
SRI OMKAR ENTERPRISES
SRI SAI TRADES
SRK ASSOCIATES
SSB ENTERPRISES
STAR ENTERPRISES
STAYSAFE SOLUTIONS PRIVATE LIMITED
STUDENT PARADISE
STURDY INTERNATIONAL
SUGANDHA TRADING SOLUTIONS
SUHANA FURNITURE
SUJATA ENTERPRISES
SUKANTA
SUKHMAN TRADERS
SUNDEEP SPORTS HOUSE
SUNIL PHARMACY
SUNIL SINGH
SUNRISE CONSTRUCTION AND SUPPLIER
SUNSHINE KOMPANY
SURAJ RATHOR
SURBHI COMPUTER SERVICE
SWADESHI WOOLLEN MILLS
SYSTEM & EQUIPMENT ENTERPRISES
Sayenjali Overseas
Seating Solution Enterprises
Shourya Enterprises
Shree Shyam Healthcare
Shree Shyam Industries
Shri Jarawari Technologies
Shrishti electrical
Shyam Enterprise
SignX India
Sriya enterprise
Sudan Enterprises
Suresh Kumar
Swastika Enterprise
T M ENTERPRISES
TEAM COMPUTERS PVT LTD
TECHKNOWSKOLA PRIVATE LIMITED
TECHMATIC SOLUTION
TEKSURVY PRIVATE LIMITED
THE AUTOMOTIVE GUYS
THE RENU ENTERPRISES
TINSUKIA TRADE AND SUPPLY
TITIKSA ENTERPRISES PRIVATE LIMITED
TONER CARE SOLUTIONS
TRADE & TECHNOLOGY
TRADE CORE ENTERPRISES
TRANSCON ELECTRONICS PVT LTD
TWENTY THREE INFRATECH
Tayal Electric & Construction Co
Tech Junction
The Rao Turaly Enterprise
Tri Angle Enterprise
Trinket Enterprises
U S ENTERPRISES
UAI ENTERPRISES
UB TRADERS
UMADUTT INDUSTRIES LIMITED
UNION ENTERPRISES
UNIQ INFOTECH
UNIQUE DESIGN AND CONSTRUCTIONS
UNIQUE SERVICES PRIVATE LIMITED
UNITED MARKETING SPORTS EMPORIUM
UNIVERSAL PRODUCTS
UPPER ASSAM FABRICATION
URBAN ROOTS
Urmila
V LINK SYSTEMS PRIVATE LIMITED
V. S. ASSOCIATES
V.N.C, ENTERPRISES
VARSA PARTNERS LLP
VEER TRADING COMPANY
VENDING UPDATES
VERMA INDUSTRIES
VERMA SPORTS
VIDHI ARMY STORE
VINAYAK ENTERPRISE
VINAYAK ENTERPRISES
VINAYAKA ENTERPRISES
VIR ENTERPRISES
VISHWA TRADERS
VISION INC
VISION INDIA
VIVADHIKA INDIA PRIVATE LIMITED
VNC ENTERPRISES
VR Enterprise
VV ENTERPRISES
Voiceroot it solutions
WANI ENTERPRISES
WASTE HANDLING EQUIPMENT MANUFACTURING ENTERPRISES
WHEM SERVICE SOLUTION PRIVATE LIMITED
WISSEN TECHUS PRIVATE LIMITED
WOSICO SCIENTIFIC WORKS
X MENINDIA
YADAV ELECTRONICS & ELECTRICALS
YESESWINI AUTOMATION
YPG TRADERS
Yes Celebration
Zenith Enterprises
akas distributors
apgraphic enterprises
bhanu badyal
eCave solutions
global engineering
jai shree balaji sales corporation
luxmy supply & co.
om sai traders
raju and raju associate
shiv computer palace
shri balaji enterprises
shri sainath enterprises
urmila banik
vikas printers

"""

company_list = raw_text.strip().split('\n')
import pandas as pd
import os
from glob import glob
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# Step 1: Define path and company list
folder = r'C:\vs_code\TenderHunter2.1.3\final\paladiam\result'

# Step 2: Normalize function
def normalize_name(name):
    if pd.isna(name): return ""
    name = str(name).upper().replace('(MII)', '').strip()
    name = name.replace('.', '').replace(',', '')
    return ' '.join(name.split())

normalized_companies = [normalize_name(name) for name in company_list]

# Step 3: Load all CSVs
all_files = glob(os.path.join(folder, "*.csv"))
df_list = [pd.read_csv(file) for file in all_files]
df = pd.concat(df_list, ignore_index=True)

# Step 4: Normalize company name
df['company_name_clean'] = df['company_name'].apply(normalize_name)

# Step 5: Filter only matched companies
df = df[df['company_name_clean'].isin(normalized_companies)].copy()

# Step 6: Add necessary columns
df['Sn'] = None
df['count'] = df.groupby('company_name_clean')['company_name_clean'].transform('count')
df['Item_description'] = df['title']
df['start_date'] = df['status_update_date']
df['tender_value'] = df['result_bid_value']
df['Amount'] = df['bid_amount']
df['Tender_id'] = df['ref_no']
df['Name'] = df['company_name_clean']
df['organisation'] = df['organisation']


# Step 7: Select columns
columns = ['Sn', 'count', 'Name', 'Tender_id',"organisation", 'Item_description', 'start_date', 'tender_value', 'Amount']
df = df[columns]

# Step 8: Assign Sn by group
df['Sn'] = df.groupby('Name', sort=False).ngroup() + 1

# Step 9: Sort for grouping
df = df.sort_values(by=['Sn', 'Tender_id'])

# Step 10: Export to Excel
output_path = os.path.join('asasgrouped_output_colored.xlsx')
df.to_excel(output_path, index=False)

# Step 11: Apply Color Coding with openpyxl
wb = load_workbook(output_path)
ws = wb.active

# Define colors
fill_white = PatternFill(start_color='FFFFFF', end_color='FFFFFF', fill_type='solid')
fill_gray = PatternFill(start_color='DDDDDD', end_color='DDDDDD', fill_type='solid')

current_sn = None
fill_toggle = True

# Start from row 2 (row 1 = headers)
for i, row in enumerate(ws.iter_rows(min_row=2, max_row=ws.max_row), start=2):
    sn_value = ws[f"A{i}"].value
    if sn_value != current_sn:
        fill_toggle = not fill_toggle
        current_sn = sn_value
    fill = fill_gray if fill_toggle else fill_white
    for cell in row:
        cell.fill = fill

wb.save(output_path)

print("✅ Grouped and color-coded output saved at:", output_path)
